firefox:
  aliases:
    - firefox
    - navegador

  executable:
    linux: firefox
    windows: firefox.exe
    macos: Firefox

chrome:
  aliases:
    - chrome
    - google
    - google chrome

  executable:
    linux: google-chrome
    windows: chrome.exe
    macos: Google Chrome

vscode:
  aliases:
    - vscode
    - code
    - visual studio code
    - visual

  executable:
    linux: code
    windows: Code.exe
    macos: Visual Studio Code

terminal:
  aliases:
    - terminal
    - consola

  executable:
    linux: gnome-terminal
    windows: cmd.exe
    macos: Terminal